Topic/atk fix speed of sound
supercollider/sc3-plugins pull request #319
Opened 2021-07-27 18:14 UTC by joslloand

PR to address #317 (& ATK Quark [104](https://github.com/ambisonictoolkit/atk-sc3/issues/104))

Additional updates to [ATK sc3-plugins README](https://github.com/supercollider/sc3-plugins/blob/main/source/ATK/sc/README.md) to align with [ATK Quark README](https://github.com/ambisonictoolkit/atk-sc3/blob/master/README.md) & in preparation for sc3-plugins v3.12.0 release.

2021-07-27 18:22 UTC, dyfer commented
Hi @joslloand 
I haven't looked at this closely, but wouldn't it be possible to have this value set from sclang?

2021-07-27 18:24 UTC, joshpar requested changes

2021-07-27 18:24 UTC, joshpar commented on source/ATK/AtkUGens.cpp
> +		float freq = 54.59014548052 / distanceStart;
I think this is a good opportunity to store this value into a C constant, and that constant is used instead of the 54.590 ... etc.

2021-07-27 18:40 UTC, joslloand commented on source/ATK/AtkUGens.cpp
> +		float freq = 54.59014548052 / distanceStart;
Good idea!

2021-07-27 18:48 UTC, dyfer commented on source/ATK/AtkUGens.cpp
> +		float freq = 54.59014548052 / distanceStart;
Sorry if this is out of scope, but wouldn't we want to be able to change speed of sound? It depends on environmental factors, after all...

2021-07-27 18:56 UTC, joslloand commented
> I haven't looked at this closely, but wouldn't it be possible to have this value set from sclang?
@dyfer, ah, that might be better, as it would then be changeable?

Ah, this is a nice idea!

In practice, I don't think I'd want this to be an argument that the user supplies directly in the user interface to the UGen. Doing so could / would break existing code.

Instead, it should happen "under the hood" by setting `AtkFoa.speedOfSound` to the relevant value.

---
Ok, having had a little look, the changes to do so would have to happen in both [AtkUGens.cpp](https://github.com/supercollider/sc3-plugins/blob/main/source/ATK/AtkUGens.cpp) here in sc3-plugins, and in [ATK.sc](https://github.com/ambisonictoolkit/atk-sc3/blob/dev/Classes/ATK.sc#L950-L973) found in the quark.

@joshpar, what do you think of this?

2021-07-27 19:02 UTC, dyfer commented
> Instead, it should happen "under the hood" by setting `AtkFoa.speedOfSound` to the relevant value.

Yes, that's what I was thinking

2021-07-27 19:14 UTC, joslloand commented
> > Instead, it should happen "under the hood" by setting `AtkFoa.speedOfSound` to the relevant value.
> 
> Yes, that's what I was thinking

Good to know!

The _slight_ danger is that users will need to _make sure_ to update both sc3-plugins and the atk-sc3 quark. That shouldn't be a problem if the change is communicated in the update announcement..

@joshpar, how does this sound to you. (I'll add @mtmccrea, too.)

2021-07-27 19:19 UTC, joshpar commented
yeah @joslloand - I think that's a cool idea

2021-07-27 19:31 UTC, joslloand commented
> yeah @joslloand - I think that's a cool idea

Ok, great!

As for actually making it happen, I'm _super rusty_ on the plugin side and would need to have some guidance on getting it right.

In particular, once the speed of sound is set, it _should_ be constant for the life of the UGen instantiation. I.e., it _should_ be a fixed value that isn't modulate-able.

@dyfer, I may reach out over email for a quick chat on the matter....

2021-07-27 19:33 UTC, joshpar commented
I can help as well if needed. Cheers!

> On Jul 27, 2021, at 12:32, Joseph Anderson ***@***.***> wrote:
> 
> 
> yeah @joslloand <https://github.com/joslloand> - I think that's a cool idea
> 
> Ok, great!
> 
> As for actually making it happen, I'm super rusty on the plugin side and would need to have some guidance on getting it right.
> 
> In particular, once the speed of sound is set, it should be constant for the life of the UGen instantiation. I.e., it should be a fixed value that isn't modulate-able.
> 
> @dyfer <https://github.com/dyfer>, I may reach out over email for a quick chat on the matter....
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/supercollider/sc3-plugins/pull/319#issuecomment-887777993>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAANHLALDVOQLR4FNPU2IZLTZ4CTFANCNFSM5BCYNZBA>.
>

2021-07-27 19:36 UTC, joslloand commented
> I can help as well if needed. Cheers!

Ok, great! I think I see what needs to happen... so that's fine. (However, since, I haven't tried to compile sc3-plugins on this machine in so long, I'm expecting a task!)

2021-07-27 22:44 UTC, joslloand commented on source/ATK/AtkUGens.cpp
> +		float freq = 54.59014548052 / distanceStart;
Agreed... my latest push could be the thing...

2021-07-27 22:46 UTC, joslloand commented
Ok, I've just made an updated push.

The updated atk-sc3 quark branch is here: https://github.com/ambisonictoolkit/atk-sc3/tree/refactor-foa-nfc-proximity

What I haven't done is tried to compile... so testing is required....

2021-08-06 17:18 UTC, dyfer commented
@joslloand we've just added automated building with github actions. If you rebase your PR on the current `main`, you'll see an automated build in this PR, where you can also download the build artifacts to test. However, building locally is definitely recommended :)

2021-08-09 09:50 UTC, mtmccrea commented on source/ATK/AtkUGens.cpp
> +		float wc = (speedOfSound / distanceStart) * SAMPLEDUR;
A minor issue but there's the opportunity to factor out `speedOfSound * SAMPLEDUR` here, as well as to check whether `distanceStart` differs from the previous block, and if it doesn't then
```
float wc = (speedOfSound / distance[i]) * SAMPLEDUR;
float a0 = 1 / (sqrt((cos(wc) * -2) + 2) + 1);
```
need not be re-calculated. I don't have a strong feeling about this kind of change at the moment, because it's quite clean as is.

2021-08-09 09:55 UTC, mtmccrea commented on source/ATK/AtkUGens.cpp
> +		float wc = (speedOfSound / distanceStart) * SAMPLEDUR;
Factoring out `speedOfSound * SAMPLEDUR` would be a matter of saving this value as a member var in the `Ctor`.

2021-08-10 01:46 UTC, joslloand commented
> @joslloand we've just added automated building with github actions. If you rebase your PR on the current `main`, you'll see an automated build in this PR, where you can also download the build artifacts to test. However, building locally is definitely recommended :)

Thanks @dyfer! I didn't realize this... very convenient. (I ended up doing a merge rather than a rebase.)

I've done some tests, and both HOA and FOA are now matched. Hurrah! So the updates are working now.

... so... I think we're ready for a merge

2021-08-10 01:48 UTC, joslloand commented on source/ATK/AtkUGens.cpp
> +		float wc = (speedOfSound / distanceStart) * SAMPLEDUR;
@mtmccrea, thanks for having a look here.

I'm not super keen as to tracking down optimizations with this update. We won't be running any slower than the previous incarnation, so it doesn't really feel especially worth it.

There is an argument to be made for an optimization sweep on the plugins further down the line, maybe....

2021-08-12 11:22 UTC, mtmccrea commented on source/ATK/AtkUGens.cpp
> +		float wc = (speedOfSound / distanceStart) * SAMPLEDUR;
@joslloand I agree, we can revisit it if @dyfer wants to encode 500 nf sources in realtime and needs a little headroom ;)

2021-08-31 00:06 UTC, joslloand commented
> > @joslloand we've just added automated building with github actions. If you rebase your PR on the current `main`, you'll see an automated build in this PR, where you can also download the build artifacts to test. However, building locally is definitely recommended :)
> 
> Thanks @dyfer! I didn't realize this... very convenient. (I ended up doing a merge rather than a rebase.)
> 
> I've done some tests, and both HOA and FOA are now matched. Hurrah! So the updates are working now.
> 
> ... so... I think we're ready for a merge

@dyfer, @joshpar just picking this up again after some time away....

... I think this is all ready to go. The tests (matching NFE results w/ the HOA implementation) have passed.

So, I think this is ready to be closed and merged.

2021-09-16 07:12 UTC, telephon commented
@joshpar would you also agree that it is ready to go?

2021-09-16 17:51 UTC, joslloand commented
> @joshpar would you also agree that it is ready to go?

@telephon I had a conversation with @dyfer yesterday, regarding backwards compatibility and resulting behavior given installs with mismatched quark and sc3-plugins.

I have a possible solution I'll be testing today that _should_ resolve performance issues if the class and plugin aren't aligned. (I expect a simple check on inputs will do the job.)

If this does work, I'll go ahead and push this change... then I think we'll _really_ be ready to go!

2021-09-16 21:45 UTC, joslloand commented
> @telephon I had a conversation with @dyfer yesterday, regarding backwards compatibility and resulting behavior given installs with mismatched quark and sc3-plugins.
> 
> I have a possible solution I'll be testing today that _should_ resolve performance issues if the class and plugin aren't aligned. (I expect a simple check on inputs will do the job.)
> 
> If this does work, I'll go ahead and push this change... then I think we'll _really_ be ready to go!

Ok, here's the fix: https://github.com/supercollider/sc3-plugins/pull/319/commits/8bc45e42374293968a26f0654d2ce4420105ddcf

Which meets these cases, testing cases for matching and unmatching quark AND plugins:

1) matching: **latest test quark** (refactor-foa-nfc-proximity) AND **latest test plugins** (topic/atk-fix-speedOfSound)
--> pass: speed of sound updated to 343 m/s

2) NOT matching: **previous released quark** (v5.0.3) AND **latest test plugins** (topic/atk-fix-speedOfSound)
--> pass: speed of sound remains at 333 m/s [ plugins supply missing speed of sound ]

3) NOT matching: **latest test quark** (refactor-foa-nfc-proximity) AND **previous plugins** (v3.11.1)
--> pass: speed of sound remains at 333 m/s [ plugins cutoff frequency sets equivalent speed of sound, value supplied by class is ignored ]

@joshpar, @dyfer, @telephon, so _now_ I'm thinking we're ready to go with this.

(Finally!)

2021-09-17 00:14 UTC, dyfer commented
This seems to work as advertised, thank you!

@joshpar @telephon is it OK to leave that merge commit in?

2021-09-17 00:15 UTC, joshpar commented
SHIP IT!

> On Sep 16, 2021, at 17:14, Marcin Pączkowski ***@***.***> wrote:
> 
> 
> This seems to work as advertised, thank you!
> 
> @joshpar <https://github.com/joshpar> @telephon <https://github.com/telephon> is it OK to leave that merge commit in?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/supercollider/sc3-plugins/pull/319#issuecomment-921349133>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAANHLAG43567L2YNH5MCVDUCKB7RANCNFSM5BCYNZBA>.
>

2021-09-17 00:18 UTC, dyfer approved these changes
Shippin' it

2021-09-17 00:19 UTC, dyfer commented
@joshpar is your change request satisfied? :)

2021-09-17 01:49 UTC, merged

2021-09-17 18:03 UTC, joslloand commented
Thanks everyone!