Add TrigPhasor
supercollider/sc3-plugins pull request #323
Opened 2021-08-14 15:29 UTC by artfwo

This is a Phasor-like helper UGen, originally implemented in [monome norns](https://github.com/monome/norns), which provides an additional trigger output that becomes positive when TrigPhasor reaches the end of its ramp.

2021-09-16 07:10 UTC, telephon requested changes

2021-09-16 07:10 UTC, telephon commented on source/TrigPhasor/sc/HelpSource/Classes/TrigPhasor.schelp
> +TrigPhasor attempts to be compatible with the Phasor UGen and
if it is compatible, then better write "TrigPhasor is full compatible with the …"

2021-09-16 07:10 UTC, telephon commented on source/TrigPhasor/sc/HelpSource/Classes/TrigPhasor.schelp
> +
Could you please add a comment on what problem this solves, i.e. why one cannot do the same with Phasor? Couldn't you just derive that trigger with a `HPZ1.ar(phasorOut) < 0`

2021-09-18 15:30 UTC, artfwo commented on source/TrigPhasor/sc/HelpSource/Classes/TrigPhasor.schelp
> +
I didn't know about HPZ1.ar and, yes, this logic can be implemented with `HPZ1.ar(phasorOut) < 0`. Will it also work when the Phasor ramp is going down, i.e. from 1 to 0?

2021-09-19 20:50 UTC, telephon commented on source/TrigPhasor/sc/HelpSource/Classes/TrigPhasor.schelp
> +
I think so:
```supercollider

(
{
var p, t;
	p = Phasor.ar(Impulse.ar(300), 1/300, 0, 1);
	t = HPZ1.ar(p) < 0;
	[p, Trig1.ar(t, 0.0002)]
	
}.plot
)



(
{
var p, t;
	p = Phasor.ar(Impulse.ar(300), -1/300, 1, 0);
	t = HPZ1.ar(p) < 0;
	[p, Trig1.ar(t, 0.0002)]
	
}.plot
)
```

2021-09-19 20:51 UTC, telephon commented on source/TrigPhasor/sc/HelpSource/Classes/TrigPhasor.schelp
> +
but test it yourself, please … :)

2021-09-20 05:32 UTC, artfwo commented on source/TrigPhasor/sc/HelpSource/Classes/TrigPhasor.schelp
> +
Thanks, this works great :) Closing this PR as no longer necessary.

2021-09-20 05:32 UTC, closed without merging

2021-09-20 06:19 UTC, telephon commented on source/TrigPhasor/sc/HelpSource/Classes/TrigPhasor.schelp
> +
Please do feel free to reopen if it tunrs out to be an incomplete solution …